// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/banners": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "管理员可按状态筛选轮播图",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-轮播"
                ],
                "summary": "管理员查询轮播图列表",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "是否启用 true/false",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.BannerResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "管理员上传图片并配置跳转链接、可见角色等信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-轮播"
                ],
                "summary": "管理员创建轮播图",
                "parameters": [
                    {
                        "description": "轮播图信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminCreateBannerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.BannerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/banners/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "管理员可修改轮播图基础信息、状态及可见范围",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-轮播"
                ],
                "summary": "管理员更新轮播图",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "轮播图ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "轮播图信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminUpdateBannerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.BannerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/contents": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "管理员可按分类、类型与状态筛选内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-内容"
                ],
                "summary": "管理员查询内容列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类ID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "内容类型(doc/video)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "内容状态(draft/published/offline)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ContentResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "管理员上传文件并设置分类、可见角色后创建内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-内容"
                ],
                "summary": "管理员创建内容",
                "parameters": [
                    {
                        "description": "内容信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminCreateContentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ContentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/contents/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "管理员可修改内容基础信息、状态与可见范围",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-内容"
                ],
                "summary": "管理员更新内容",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "内容ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "内容信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminUpdateContentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ContentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/employees": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "只有管理员可以创建新的员工账号，可同时绑定多个店长",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-用户"
                ],
                "summary": "管理员创建员工",
                "parameters": [
                    {
                        "description": "员工信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminCreateEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/managers": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "只有管理员可以创建新的店长账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-用户"
                ],
                "summary": "管理员创建店长",
                "parameters": [
                    {
                        "description": "店长信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminCreateManagerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/managers": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "覆盖式更新某个员工绑定的店长工号列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-用户"
                ],
                "summary": "管理员维护员工店长绑定",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "员工ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "店长工号列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminUpdateEmployeeManagersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/promote-manager": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "将指定员工升级为店长角色",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台-用户"
                ],
                "summary": "管理员升级店长",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/banners": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "返回当前登录用户基于角色可见的轮播图列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "轮播"
                ],
                "summary": "查询可见轮播图",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.BannerResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/contents": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "根据分类与类型筛选当前用户可访问的已发布内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内容"
                ],
                "summary": "查询已发布内容",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类ID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "内容类型(doc/video)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ContentResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/contents/categories": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "返回当前登录用户基于角色可访问的内容分类列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内容"
                ],
                "summary": "查询可见内容分类",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ContentCategoryResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/contents/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取指定已发布内容的详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内容"
                ],
                "summary": "查询内容详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "内容ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ContentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "登录用户上传文件后返回可用于内容配置的存储路径",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "待上传文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/learning": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "返回当前用户所有已记录的学习进度",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学习"
                ],
                "summary": "查询学习进度列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.LearningProgressResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "登录用户上报视频播放位置，系统会累计已学进度",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学习"
                ],
                "summary": "记录学习进度",
                "parameters": [
                    {
                        "description": "学习进度",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LearningProgressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.LearningProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/learning/{content_id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "返回当前用户在某个内容上的进度详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学习"
                ],
                "summary": "查询指定内容的学习进度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "内容ID",
                        "name": "content_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.LearningProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/login": {
            "post": {
                "description": "使用工号+密码登录，返回访问令牌与刷新令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/managers": {
            "get": {
                "description": "返回所有启用状态的店长供员工注册或绑定使用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查询店长列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.UserResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/users/me": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "返回当前登录用户的详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me/profile": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "登录用户可更新姓名与手机号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改个人信息",
                "parameters": [
                    {
                        "description": "个人信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/register": {
            "post": {
                "description": "员工填写工号、姓名、手机号与密码完成注册，可同时选择多个店长工号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "员工注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/token/refresh": {
            "post": {
                "description": "使用 refresh_token 换取新的访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新令牌请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "返回服务运行状态与当前时间",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "返回当前部署的应用名称与版本",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "查询服务版本",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AdminCreateBannerRequest": {
            "type": "object",
            "required": [
                "image_url",
                "link_url",
                "title"
            ],
            "properties": {
                "end_at": {
                    "description": "结束时间",
                    "type": "string",
                    "example": "2024-12-31T23:59:59Z"
                },
                "image_url": {
                    "description": "图片URL",
                    "type": "string",
                    "example": "https://example.com/banner.jpg"
                },
                "link_url": {
                    "description": "跳转链接",
                    "type": "string",
                    "example": "https://example.com/promotion"
                },
                "sort_order": {
                    "description": "排序序号",
                    "type": "integer",
                    "example": 1
                },
                "start_at": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "description": "是否启用",
                    "type": "boolean",
                    "example": true
                },
                "title": {
                    "description": "轮播图标题",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "春季促销活动"
                },
                "visible_roles": {
                    "description": "可见角色：employee(员工) manager(店长) both(全部)",
                    "type": "string",
                    "enum": [
                        "employee",
                        "manager",
                        "both"
                    ],
                    "example": "both"
                }
            }
        },
        "dto.AdminCreateContentRequest": {
            "type": "object",
            "required": [
                "category_id",
                "file_path",
                "title",
                "type"
            ],
            "properties": {
                "category_id": {
                    "description": "分类ID",
                    "type": "integer",
                    "example": 1
                },
                "cover_url": {
                    "description": "封面图片URL",
                    "type": "string",
                    "example": "https://example.com/cover.jpg"
                },
                "duration_seconds": {
                    "description": "视频时长（秒）",
                    "type": "integer",
                    "example": 3600
                },
                "file_path": {
                    "description": "文件存储路径",
                    "type": "string",
                    "example": "/uploads/video.mp4"
                },
                "status": {
                    "description": "状态：draft(草稿) published(已发布)",
                    "type": "string",
                    "enum": [
                        "draft",
                        "published"
                    ],
                    "example": "published"
                },
                "summary": {
                    "description": "内容摘要",
                    "type": "string",
                    "example": "本视频介绍产品核心功能"
                },
                "title": {
                    "description": "内容标题",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "产品培训视频"
                },
                "type": {
                    "description": "内容类型：doc(文档) 或 video(视频)",
                    "type": "string",
                    "enum": [
                        "doc",
                        "video"
                    ],
                    "example": "video"
                },
                "visible_roles": {
                    "description": "可见角色：employee(员工) manager(店长) both(全部)",
                    "type": "string",
                    "enum": [
                        "employee",
                        "manager",
                        "both"
                    ],
                    "example": "both"
                }
            }
        },
        "dto.AdminCreateEmployeeRequest": {
            "type": "object",
            "required": [
                "manager_ids",
                "name",
                "password",
                "work_no"
            ],
            "properties": {
                "manager_ids": {
                    "description": "店长工号列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "M001",
                        "M002"
                    ]
                },
                "name": {
                    "description": "姓名",
                    "type": "string",
                    "maxLength": 100,
                    "example": "张三"
                },
                "password": {
                    "description": "密码（至少6位）",
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "maxLength": 20,
                    "example": "13800138000"
                },
                "work_no": {
                    "description": "工号",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "E001"
                }
            }
        },
        "dto.AdminCreateManagerRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "work_no"
            ],
            "properties": {
                "name": {
                    "description": "姓名",
                    "type": "string",
                    "maxLength": 100,
                    "example": "李店长"
                },
                "password": {
                    "description": "密码（至少6位）",
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "maxLength": 20,
                    "example": "13800138000"
                },
                "work_no": {
                    "description": "工号",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "M001"
                }
            }
        },
        "dto.AdminUpdateBannerRequest": {
            "type": "object",
            "properties": {
                "end_at": {
                    "description": "结束时间",
                    "type": "string",
                    "example": "2024-12-31T23:59:59Z"
                },
                "image_url": {
                    "description": "图片URL",
                    "type": "string",
                    "example": "https://example.com/banner.jpg"
                },
                "link_url": {
                    "description": "跳转链接",
                    "type": "string",
                    "example": "https://example.com/promotion"
                },
                "sort_order": {
                    "description": "排序序号",
                    "type": "integer",
                    "example": 1
                },
                "start_at": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "description": "是否启用",
                    "type": "boolean",
                    "example": true
                },
                "title": {
                    "description": "轮播图标题",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "春季促销活动(更新)"
                },
                "visible_roles": {
                    "description": "可见角色：employee(员工) manager(店长) both(全部)",
                    "type": "string",
                    "enum": [
                        "employee",
                        "manager",
                        "both"
                    ],
                    "example": "both"
                }
            }
        },
        "dto.AdminUpdateContentRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "分类ID",
                    "type": "integer",
                    "example": 1
                },
                "cover_url": {
                    "description": "封面图片URL",
                    "type": "string",
                    "example": "https://example.com/cover.jpg"
                },
                "duration_seconds": {
                    "description": "视频时长（秒）",
                    "type": "integer",
                    "example": 3600
                },
                "file_path": {
                    "description": "文件存储路径",
                    "type": "string",
                    "example": "/uploads/video.mp4"
                },
                "status": {
                    "description": "状态：draft(草稿) published(已发布) offline(下线)",
                    "type": "string",
                    "enum": [
                        "draft",
                        "published",
                        "offline"
                    ],
                    "example": "published"
                },
                "summary": {
                    "description": "内容摘要",
                    "type": "string",
                    "example": "本视频介绍产品核心功能"
                },
                "title": {
                    "description": "内容标题",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "产品培训视频(更新)"
                },
                "type": {
                    "description": "内容类型：doc(文档) 或 video(视频)",
                    "type": "string",
                    "enum": [
                        "doc",
                        "video"
                    ],
                    "example": "video"
                },
                "visible_roles": {
                    "description": "可见角色：employee(员工) manager(店长) both(全部)",
                    "type": "string",
                    "enum": [
                        "employee",
                        "manager",
                        "both"
                    ],
                    "example": "both"
                }
            }
        },
        "dto.AdminUpdateEmployeeManagersRequest": {
            "type": "object",
            "required": [
                "manager_ids"
            ],
            "properties": {
                "manager_ids": {
                    "description": "店长工号列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "M001",
                        "M002"
                    ]
                }
            }
        },
        "dto.BannerResponse": {
            "type": "object",
            "properties": {
                "end_at": {
                    "description": "结束时间",
                    "type": "string",
                    "example": "2024-12-31T23:59:59Z"
                },
                "id": {
                    "description": "轮播图ID",
                    "type": "integer",
                    "example": 1
                },
                "image_url": {
                    "description": "图片URL",
                    "type": "string",
                    "example": "https://example.com/banner.jpg"
                },
                "link_url": {
                    "description": "跳转链接",
                    "type": "string",
                    "example": "https://example.com/promotion"
                },
                "sort_order": {
                    "description": "排序序号",
                    "type": "integer",
                    "example": 1
                },
                "start_at": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "description": "是否启用",
                    "type": "boolean",
                    "example": true
                },
                "title": {
                    "description": "轮播图标题",
                    "type": "string",
                    "example": "春季促销活动"
                },
                "visible_roles": {
                    "description": "可见角色：employee(员工) manager(店长) both(全部)",
                    "type": "string",
                    "example": "both"
                }
            }
        },
        "dto.ContentCategoryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "分类ID",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "分类名称",
                    "type": "string",
                    "example": "产品培训"
                },
                "role_scope": {
                    "description": "可见角色范围：employee(员工) manager(店长) both(全部)",
                    "type": "string",
                    "example": "both"
                },
                "sort_order": {
                    "description": "排序序号",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.ContentResponse": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "分类ID",
                    "type": "integer",
                    "example": 1
                },
                "category_name": {
                    "description": "分类名称",
                    "type": "string",
                    "example": "产品培训"
                },
                "cover_url": {
                    "description": "封面图片URL",
                    "type": "string",
                    "example": "https://example.com/cover.jpg"
                },
                "duration_seconds": {
                    "description": "视频时长（秒）",
                    "type": "integer",
                    "example": 3600
                },
                "file_path": {
                    "description": "文件存储路径",
                    "type": "string",
                    "example": "/uploads/video.mp4"
                },
                "id": {
                    "description": "内容ID",
                    "type": "integer",
                    "example": 1
                },
                "publish_at": {
                    "description": "发布时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "description": "状态：draft(草稿) published(已发布) offline(下线)",
                    "type": "string",
                    "example": "published"
                },
                "summary": {
                    "description": "内容摘要",
                    "type": "string",
                    "example": "本视频介绍产品核心功能"
                },
                "title": {
                    "description": "内容标题",
                    "type": "string",
                    "example": "产品培训视频"
                },
                "type": {
                    "description": "内容类型：doc(文档) 或 video(视频)",
                    "type": "string",
                    "example": "video"
                },
                "visible_roles": {
                    "description": "可见角色：employee(员工) manager(店长) both(全部)",
                    "type": "string",
                    "example": "both"
                }
            }
        },
        "dto.LearningProgressRequest": {
            "type": "object",
            "required": [
                "content_id",
                "video_position"
            ],
            "properties": {
                "content_id": {
                    "description": "内容ID",
                    "type": "integer",
                    "example": 1
                },
                "video_position": {
                    "description": "视频播放位置（秒）",
                    "type": "integer",
                    "minimum": 0,
                    "example": 120
                }
            }
        },
        "dto.LearningProgressResponse": {
            "type": "object",
            "properties": {
                "content_id": {
                    "description": "内容ID",
                    "type": "integer",
                    "example": 1
                },
                "duration_seconds": {
                    "description": "视频总时长（秒）",
                    "type": "integer",
                    "example": 3600
                },
                "progress": {
                    "description": "学习进度百分比（0-100）",
                    "type": "integer",
                    "example": 3
                },
                "status": {
                    "description": "学习状态：not_started(未开始) in_progress(进行中) completed(已完成)",
                    "type": "string",
                    "example": "in_progress"
                },
                "video_position": {
                    "description": "视频播放位置（秒）",
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "work_no"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123456"
                },
                "work_no": {
                    "description": "工号",
                    "type": "string",
                    "example": "E001"
                }
            }
        },
        "dto.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "manager_ids",
                "password",
                "work_no"
            ],
            "properties": {
                "manager_ids": {
                    "description": "店长工号列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "M001",
                        "M002"
                    ]
                },
                "name": {
                    "description": "姓名",
                    "type": "string",
                    "maxLength": 100,
                    "example": "张三"
                },
                "password": {
                    "description": "密码（至少6位）",
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "maxLength": 20,
                    "example": "13800138000"
                },
                "work_no": {
                    "description": "工号",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "E001"
                }
            }
        },
        "dto.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "姓名",
                    "type": "string",
                    "maxLength": 100,
                    "example": "张三"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "maxLength": 20,
                    "example": "13800138000"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "姓名",
                    "type": "string",
                    "example": "张三"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "example": "13800138000"
                },
                "role": {
                    "description": "角色：employee(员工) manager(店长) admin(管理员)",
                    "type": "string",
                    "example": "employee"
                },
                "status": {
                    "description": "状态：true(启用) false(禁用)",
                    "type": "boolean",
                    "example": true
                },
                "work_no": {
                    "description": "工号",
                    "type": "string",
                    "example": "E001"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "使用 \"Bearer {token}\" 格式，token 通过登录接口获取",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Mini Study API",
	Description:      "企业学习平台后端 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
